python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch1  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch2  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch3  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch4  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch5  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch6  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch7  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch8  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch9  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch10  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch11  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch12  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini

python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch13  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin ch14  -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini

