bash runAll.sh  ZH    ZvvHbb13TeV  sys >& log/logSysZH  &
bash runAll.sh  ZH_mini    ZvvHbb13TeV  sys >& log/logSysZH_mini  &
#bash runAll.sh  ZHpow     ZvvHbb13TeV sys >& log/logSysZHpow  &
bash runAll.sh  ggZH     ZvvHbb13TeV sys >& log/logSysggZH  &
#bash runAll.sh  ggZHpow     ZvvHbb13TeV sys >& log/logSysggZHpow  &
bash runAll.sh  WH     ZvvHbb13TeV sys >& log/logSysWH  &
#bash runAll.sh  WplusHpow     ZvvHbb13TeV sys >& log/logSysWplusHpow  &
#bash runAll.sh  WminusHpow     ZvvHbb13TeV sys >& log/logSysWminusHpow  &
#bash runAll.sh  WJets     ZvvHbb13TeV sys >& log/logSysWJets  &
bash runAll.sh  WJetsMadHT100     ZvvHbb13TeV sys >& log/logSysWJetsMadHT100  &
bash runAll.sh  WJetsMadHT200     ZvvHbb13TeV sys >& log/logSysWJetsMadHT200  &
bash runAll.sh  WJetsMadHT400     ZvvHbb13TeV sys >& log/logSysWJetsMadHT400  &
bash runAll.sh  WJetsMadHT600     ZvvHbb13TeV sys >& log/logSysWJetsMadHT600  &
#bash runAll.sh  ZJets     ZvvHbb13TeV sys >& log/logSysZJets  &
bash runAll.sh  ZJetsMadHT100     ZvvHbb13TeV sys >& log/logSysZJetsMadHT100  &
bash runAll.sh  ZJetsMadHT200     ZvvHbb13TeV sys >& log/logSysZJetsMadHT200  &
bash runAll.sh  ZJetsMadHT400     ZvvHbb13TeV sys >& log/logSysZJetsMadHT400  &
bash runAll.sh  ZJetsMadHT600     ZvvHbb13TeV sys >& log/logSysZJetsMadHT600  &
bash runAll.sh  TT     ZvvHbb13TeV sys >& log/logSysTT  &
#bash runAll.sh  TTPow     ZvvHbb13TeV sys >& log/logSysTTPow  &
bash runAll.sh  ST_s     ZvvHbb13TeV sys >& log/logSysST_s  &
bash runAll.sh  ST_t     ZvvHbb13TeV sys >& log/logSysST_t  &
bash runAll.sh  ST_tW_antitop     ZvvHbb13TeV sys >& log/logSysST_tW_antitop  &
bash runAll.sh  ST_tW_top     ZvvHbb13TeV sys >& log/logSysST_tW_top  &
bash runAll.sh  QCDHT100     ZvvHbb13TeV sys >& log/logSysQCDHT100  &
bash runAll.sh  QCDHT200     ZvvHbb13TeV sys >& log/logSysQCDHT200  &
bash runAll.sh  QCDHT300     ZvvHbb13TeV sys >& log/logSysQCDHT300  &
bash runAll.sh  QCDHT500     ZvvHbb13TeV sys >& log/logSysQCDHT500  &
bash runAll.sh  QCDHT700     ZvvHbb13TeV sys >& log/logSysQCDHT700  &
bash runAll.sh  QCDHT1000     ZvvHbb13TeV sys >& log/logSysQCDHT1000  &
bash runAll.sh  QCDHT1500     ZvvHbb13TeV sys >& log/logSysQCDHT1500  &
bash runAll.sh  QCDHT2000     ZvvHbb13TeV sys >& log/logSysQCDHT2000  &
bash runAll.sh  DataMET     ZvvHbb13TeV sys >& log/logSysDataMET  &

bash runAll.sh  WWpythia     ZvvHbb13TeV sys >& log/logSysWWpythia  &
#bash runAll.sh  WWTo2L2Q     ZvvHbb13TeV sys >& log/logSysWWTo2L2Q  &
#bash runAll.sh  WWTo4Q     ZvvHbb13TeV sys >& log/logSysWWTo4Q  &
#bash runAll.sh  WWTo2L2Nu     ZvvHbb13TeV sys >& log/logSysWWTo2L2Nu  &
bash runAll.sh  WZpythia     ZvvHbb13TeV sys >& log/logSysWZpythia  &
#bash runAll.sh  WZTo2L2Q     ZvvHbb13TeV sys >& log/logSysWZTo2L2Q  &
#bash runAll.sh  WZTo1L1Nu2Q     ZvvHbb13TeV sys >& log/logSysWZTo1L1Nu2Q  &
#bash runAll.sh  WZTo4Q     ZvvHbb13TeV sys >& log/logSysWZTo4Q  &
bash runAll.sh  ZZpythia     ZvvHbb13TeV sys >& log/logSysZZpythia  &
#bash runAll.sh  ZZTo2L2Q     ZvvHbb13TeV sys >& log/logSysZZTo2L2Q  &
bash runAll.sh  ZZTo2Q2Nu     ZvvHbb13TeV sys >& log/logSysZZTo2Q2Nu  &

bash runAll.sh  SingleElectron     ZvvHbb13TeV sys >& log/logSysSingleElectron  &
bash runAll.sh  SingleMuon     ZvvHbb13TeV sys >& log/logSysSingleMuon  &
bash runAll.sh  DoubleEG     ZvvHbb13TeV sys >& log/logSysDoubleEG  &
bash runAll.sh  DoubleMuon     ZvvHbb13TeV sys >& log/logSysDoubleMuon  &
bash runAll.sh  HTMHT     ZvvHbb13TeV sys >& log/logSysHTMHT  &
bash runAll.sh  MET     ZvvHbb13TeV sys >& log/logSysMET  &
bash runAll.sh  JetHT     ZvvHbb13TeV sys >& log/logSysJetHT  &
bash runAll.sh  Jet     ZvvHbb13TeV sys >& log/logSysJet  &
bash runAll.sh  MuonEG     ZvvHbb13TeV sys >& log/logSysMuonEG  &

