bash runAll.sh  ZH    ZvvHbb13TeV  vars >& log/logVarsZH  &
bash runAll.sh  ZH_mini    ZvvHbb13TeV  vars >& log/logVarsZH_mini  &
bash runAll.sh  ZHpow     ZvvHbb13TeV vars >& log/logVarsZHpow  &
bash runAll.sh  ggZH     ZvvHbb13TeV vars >& log/logVarsggZH  &
bash runAll.sh  ggZHpow     ZvvHbb13TeV vars >& log/logVarsggZHpow  &
bash runAll.sh  WH     ZvvHbb13TeV vars >& log/logVarsWH  &
bash runAll.sh  WplusHpow     ZvvHbb13TeV vars >& log/logVarsWplusHpow  &
bash runAll.sh  WminusHpow     ZvvHbb13TeV vars >& log/logVarsWminusHpow  &
bash runAll.sh  WJetsHT0     ZvvHbb13TeV vars >& log/logVarsWJetsHT0  &
bash runAll.sh  WJetsMadHT100     ZvvHbb13TeV vars >& log/logVarsWJetsMadHT100  &
bash runAll.sh  WJetsMadHT200     ZvvHbb13TeV vars >& log/logVarsWJetsMadHT200  &
bash runAll.sh  WJetsMadHT400     ZvvHbb13TeV vars >& log/logVarsWJetsMadHT400  &
bash runAll.sh  WJetsMadHT600     ZvvHbb13TeV vars >& log/logVarsWJetsMadHT600  &
bash runAll.sh  ZJetsHT0     ZvvHbb13TeV vars >& log/logVarsZJetsHT0  &
bash runAll.sh  ZJetsMadHT100     ZvvHbb13TeV vars >& log/logVarsZJetsMadHT100  &
bash runAll.sh  ZJetsMadHT200     ZvvHbb13TeV vars >& log/logVarsZJetsMadHT200  &
bash runAll.sh  ZJetsMadHT400     ZvvHbb13TeV vars >& log/logVarsZJetsMadHT400  &
bash runAll.sh  ZJetsMadHT600     ZvvHbb13TeV vars >& log/logVarsZJetsMadHT600  &
bash runAll.sh  ZJetsMadHT800            ZvvHbb13TeV vars >& log/logPrepZJetsMadHT800   &
bash runAll.sh  ZJetsMadHT1200            ZvvHbb13TeV vars >& log/logPrepZJetsMadHT1200   &
bash runAll.sh  ZJetsMadHT2500            ZvvHbb13TeV vars >& log/logPrepZJetsMadHT2500   &
bash runAll.sh  TT     ZvvHbb13TeV vars >& log/logVarsTT  &
bash runAll.sh  TTPow     ZvvHbb13TeV vars >& log/logVarsTTPow  &
bash runAll.sh  ST_s     ZvvHbb13TeV vars >& log/logVarsST_s  &
bash runAll.sh  ST_t     ZvvHbb13TeV vars >& log/logVarsST_t  &
bash runAll.sh  ST_tW_antitop     ZvvHbb13TeV vars >& log/logVarsST_tW_antitop  &
bash runAll.sh  ST_tW_top     ZvvHbb13TeV vars >& log/logVarsST_tW_top  &
bash runAll.sh  QCDHT100     ZvvHbb13TeV vars >& log/logVarsQCDHT100  &
bash runAll.sh  QCDHT200     ZvvHbb13TeV vars >& log/logVarsQCDHT200  &
bash runAll.sh  QCDHT300     ZvvHbb13TeV vars >& log/logVarsQCDHT300  &
bash runAll.sh  QCDHT500     ZvvHbb13TeV vars >& log/logVarsQCDHT500  &
bash runAll.sh  QCDHT700     ZvvHbb13TeV vars >& log/logVarsQCDHT700  &
bash runAll.sh  QCDHT1000     ZvvHbb13TeV vars >& log/logVarsQCDHT1000  &
bash runAll.sh  QCDHT1500     ZvvHbb13TeV vars >& log/logVarsQCDHT1500  &
bash runAll.sh  QCDHT2000     ZvvHbb13TeV vars >& log/logVarsQCDHT2000  &
bash runAll.sh  DataMET     ZvvHbb13TeV vars >& log/logVarsDataMET  &
bash runAll.sh	ZJetsLLHT0		 ZvvHbb13TeV vars >& log/logVarsZJetsLLHT0	    &
bash runAll.sh  ZJetsLLHT100     ZvvHbb13TeV vars >& log/logVarsZJetsLLHT100  &
bash runAll.sh  ZJetsLLHT200     ZvvHbb13TeV vars >& log/logVarsZJetsLLHT200  &
bash runAll.sh  ZJetsLLHT400     ZvvHbb13TeV vars >& log/logVarsZJetsLLHT400  &
bash runAll.sh  ZJetsLLHT600     ZvvHbb13TeV vars >& log/logVarsZJetsLLHT600  &

bash runAll.sh  WWpythia     ZvvHbb13TeV vars >& log/logVarsWWpythia  &
#bash runAll.sh  WWTo2L2Q     ZvvHbb13TeV vars >& log/logVarsWWTo2L2Q  &
#bash runAll.sh  WWTo4Q     ZvvHbb13TeV vars >& log/logVarsWWTo4Q  &
#bash runAll.sh  WWTo2L2Nu     ZvvHbb13TeV vars >& log/logVarsWWTo2L2Nu  &
bash runAll.sh  WZpythia     ZvvHbb13TeV vars >& log/logVarsWZpythia  &
#bash runAll.sh  WZTo2L2Q     ZvvHbb13TeV vars >& log/logVarsWZTo2L2Q  &
#bash runAll.sh  WZTo1L1Nu2Q     ZvvHbb13TeV vars >& log/logVarsWZTo1L1Nu2Q  &
#bash runAll.sh  WZTo4Q     ZvvHbb13TeV vars >& log/logVarsWZTo4Q  &
bash runAll.sh  ZZpythia     ZvvHbb13TeV vars >& log/logVarsZZpythia  &
#bash runAll.sh  ZZTo2L2Q     ZvvHbb13TeV vars >& log/logVarsZZTo2L2Q  &
bash runAll.sh  ZZTo2Q2Nu     ZvvHbb13TeV vars >& log/logVarsZZTo2Q2Nu  &

bash runAll.sh  FakeQCDHT100     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT100  &
bash runAll.sh  FakeQCDHT200     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT200  &
bash runAll.sh  FakeQCDHT300     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT300  &
bash runAll.sh  FakeQCDHT500     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT500  &
bash runAll.sh  FakeQCDHT700     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT700  &
bash runAll.sh  FakeQCDHT1000     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT1000  &
bash runAll.sh  FakeQCDHT1500     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT1500  &
bash runAll.sh  FakeQCDHT2000     ZvvHbb13TeV vars >& log/logVarsFakeQCDHT2000  &

bash runAll.sh  SingleElectron     ZvvHbb13TeV vars >& log/logVarsSingleElectron  &
bash runAll.sh  SingleMuon     ZvvHbb13TeV vars >& log/logVarsSingleMuon  &
bash runAll.sh  DoubleEG     ZvvHbb13TeV vars >& log/logVarsDoubleEG  &
bash runAll.sh  DoubleMuon     ZvvHbb13TeV vars >& log/logVarsDoubleMuon  &
bash runAll.sh  HTMHT     ZvvHbb13TeV vars >& log/logVarsHTMHT  &
bash runAll.sh  MET     ZvvHbb13TeV vars >& log/logVarsMET  &
bash runAll.sh  JetHT     ZvvHbb13TeV vars >& log/logVarsJetHT  &
bash runAll.sh  Jet     ZvvHbb13TeV vars >& log/logVarsJet  &
bash runAll.sh  MuonEG     ZvvHbb13TeV vars >& log/logVarsMuonEG  &

