python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_TT -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_WLight -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_Wbb -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_ZLight -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_Zbb -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_QCD -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_SR -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_TT -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_WLight -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_Wbb -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_ZLight -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_Zbb -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_QCD -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_SR -M $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/mlfit.root -F s -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini -L $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRslogMaxLikelihoodFit.txt

