python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_TT -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_WLight -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_Wbb -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_ZLight -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_Zbb -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_CR_QCD -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_HighPt_SR -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_TT -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_WLight -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_Wbb -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_ZLight -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_Zbb -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_CR_QCD -V minCSVfit -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &
python stack_from_dc.py -D $CMSSW_BASE/src/Xbb/Limit_expertAllnominal/FitTwoBinsTight/SRandCRs.txt --bin Znn_LowPt_SR -V ZvvBDT -C ZvvHbb13TeVconfig/general.ini -C ZvvHbb13TeVconfig/vhbbPlotDef.ini -C ZvvHbb13TeVconfig/plots.ini -C ZvvHbb13TeVconfig/paths.ini -C ZvvHbb13TeVconfig/datacard.ini >& log/logPlotsDCpre &

